In [2]:
import pandas as pd

In [3]:
file_path = 'nasdaq_screener_1700335987448.csv'

# Read the CSV file into a Pandas DataFrame
stock_list_df = pd.read_csv(file_path)

# Display the DataFrame
stock_list_df.head()

,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,Sector,Industry
0,A,Agilent Technologies Inc. Common Stock,$113.15,-1.04,-0.91%,3.310625e+10,United States,1999.0,2700770,Industrials,Electrical Products
1,AAPL,Apple Inc. Common Stock,$189.69,-0.02,-0.01%,2.950200e+12,United States,1980.0,50922657,Technology,Computer Manufacturing
2,ABBV,AbbVie Inc. Common Stock,$138.30,0.02,0.01%,2.441740e+11,United States,2012.0,4332297,Health Care,Biotechnology: Pharmaceutical Preparations
3,ABNB,Airbnb Inc. Class A Common Stock,$127.15,0.87,0.69%,8.244890e+10,United States,2020.0,3795704,Consumer Discretionary,Hotels/Resorts
4,ABT,Abbott Laboratories Common Stock,$99.55,-0.71,-0.71%,1.728250e+11,United States,NaN,6069070,Health Care,Biotechnology: Pharmaceutical Preparations

In [4]:
file_path2 = 'Data_df/data_DP2.csv'
file_path3 = 'Data_df/data_DP3.csv'
file_path4 = 'Data_df/data_DP4.csv'
file_path5 = 'Data_df/data_DP5.csv'
file_path6 = 'Data_df/data_DP6.csv'
file_path7 = 'Data_df/data_DP7.csv'
file_path8 = 'Data_df/data_DP8.csv'
file_path9 = 'Data_df/data_DP9.csv'
file_path10 = 'Data_df/data_DP10.csv'
file_path11 = 'Data_df/data_DP11.csv'
file_path12 = 'Data_df/data_DP12.csv'
file_path13 = 'Data_df/data_DP13.csv'
file_path14 = 'Data_df/data_DP14.csv'

In [5]:
data_DP2 = pd.read_csv(file_path2)
data_DP3 = pd.read_csv(file_path3)
data_DP4 = pd.read_csv(file_path4)
data_DP5 = pd.read_csv(file_path5)
data_DP6 = pd.read_csv(file_path6)
data_DP7 = pd.read_csv(file_path7)
data_DP8 = pd.read_csv(file_path8)
data_DP9 = pd.read_csv(file_path9)
data_DP10 = pd.read_csv(file_path10)
data_DP11 = pd.read_csv(file_path11)
data_DP12 = pd.read_csv(file_path12)
data_DP13 = pd.read_csv(file_path13)
data_DP14 = pd.read_csv(file_path14)

In [6]:
concatenated_df = pd.concat([data_DP2, data_DP3,data_DP4, data_DP5, data_DP6, data_DP7, data_DP8, data_DP9, data_DP10, data_DP11, data_DP12, data_DP13, data_DP14], ignore_index=True)

In [7]:
concatenated_df

,industry,wr1,wr2,wr3,wr4,vol1,vol2,vol3,vol4,pe_ratio,...,profit_margin,free_cash_margin,volatility,cpi,interest_rate,unemployment_rate,sma,rsi,ema,label
0,Consumer Discretionary,-0.019375,0.042774,-0.009555,-0.007692,6230100,6996900,6377700,7026700,30.01,...,14.40,13.74,0.025251,241.428,0.40,5.0,56.240000,8.149406,56.300000,0
1,Utilities,0.025644,0.011924,-0.006826,0.031470,175800,195300,233900,221400,17.58,...,11.15,1.49,0.013118,238.132,0.36,5.0,73.803333,87.796610,73.714583,0
2,Real Estate,0.057182,-0.004482,-0.040843,0.036994,1298900,3493600,571100,832500,62.13,...,12.97,29.98,0.019104,237.838,0.13,5.0,23.196667,88.260870,23.240833,0
3,Industrials,-0.044857,0.062964,0.055392,-0.058078,1071300,880100,1080400,994800,6.68,...,27.43,-18.14,0.023650,305.691,5.08,3.5,235.736667,11.037986,235.240833,0
4,Consumer Staples,0.022806,-0.021995,0.021842,-0.028000,6563300,6745100,9474700,10172500,10.28,...,4.55,10.21,0.019597,259.101,0.10,10.2,63.633333,72.448980,63.837083,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,Health Care,-0.006392,0.002918,-0.015773,-0.027340,1216800,1437600,1177900,2002900,11.71,...,6.66,8.22,0.021537,307.671,5.33,3.9,241.966667,47.654269,242.027500,1
545,Consumer Discretionary,0.035572,-0.015410,-0.015177,-0.004942,23388500,10904900,7646100,7646100,5.63,...,4.60,-5.13,0.018435,242.839,0.66,4.7,36.210000,62.500000,36.228333,0
546,Finance,0.006934,0.029712,-0.002174,0.087891,616500,855300,664000,765100,31.62,...,32.72,27.00,0.020766,289.109,0.33,3.6,342.393333,65.600000,342.544167,0
547,Real Estate,0.042916,0.015226,-0.017039,0.026714,1736300,2192100,2849100,2264600,188.50,...,8.43,-63.99,0.017338,264.877,0.07,6.1,45.173333,71.673820,44.983750,0
548,Technology,-0.091923,-0.005320,-0.060329,0.035899,4395300,4512100,3289400,4152500,23.46,...,45.80,17.29,0.042759,289.109,0.33,3.6,101.606667,32.304038,102.040833,1

In [8]:
final_df = concatenated_df.dropna()

In [9]:
final_df

,industry,wr1,wr2,wr3,wr4,vol1,vol2,vol3,vol4,pe_ratio,...,profit_margin,free_cash_margin,volatility,cpi,interest_rate,unemployment_rate,sma,rsi,ema,label
0,Consumer Discretionary,-0.019375,0.042774,-0.009555,-0.007692,6230100,6996900,6377700,7026700,30.01,...,14.40,13.74,0.025251,241.428,0.40,5.0,56.240000,8.149406,56.300000,0
1,Utilities,0.025644,0.011924,-0.006826,0.031470,175800,195300,233900,221400,17.58,...,11.15,1.49,0.013118,238.132,0.36,5.0,73.803333,87.796610,73.714583,0
2,Real Estate,0.057182,-0.004482,-0.040843,0.036994,1298900,3493600,571100,832500,62.13,...,12.97,29.98,0.019104,237.838,0.13,5.0,23.196667,88.260870,23.240833,0
3,Industrials,-0.044857,0.062964,0.055392,-0.058078,1071300,880100,1080400,994800,6.68,...,27.43,-18.14,0.023650,305.691,5.08,3.5,235.736667,11.037986,235.240833,0
4,Consumer Staples,0.022806,-0.021995,0.021842,-0.028000,6563300,6745100,9474700,10172500,10.28,...,4.55,10.21,0.019597,259.101,0.10,10.2,63.633333,72.448980,63.837083,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Technology,0.003835,0.116087,0.006430,0.019776,7664800,6601000,5447300,6911900,15.85,...,43.79,37.70,0.023855,297.711,3.83,3.6,175.463333,52.841561,175.392083,0
544,Health Care,-0.006392,0.002918,-0.015773,-0.027340,1216800,1437600,1177900,2002900,11.71,...,6.66,8.22,0.021537,307.671,5.33,3.9,241.966667,47.654269,242.027500,1
545,Consumer Discretionary,0.035572,-0.015410,-0.015177,-0.004942,23388500,10904900,7646100,7646100,5.63,...,4.60,-5.13,0.018435,242.839,0.66,4.7,36.210000,62.500000,36.228333,0
546,Finance,0.006934,0.029712,-0.002174,0.087891,616500,855300,664000,765100,31.62,...,32.72,27.00,0.020766,289.109,0.33,3.6,342.393333,65.600000,342.544167,0
548,Technology,-0.091923,-0.005320,-0.060329,0.035899,4395300,4512100,3289400,4152500,23.46,...,45.80,17.29,0.042759,289.109,0.33,3.6,101.606667,32.304038,102.040833,1

In [10]:
final_df.to_csv('data_df/final_data_DP.csv', index=False)

In [11]:
path_DP = 'Data_df/final_data_DP.csv'
path_AP = 'Data_df/final_data_AP.csv'
path_GJ = 'Data_df/final_data_GJ.csv'
path_JB = 'Data_df/final_data_JB.csv'

data_DPF = pd.read_csv(path_DP)
data_APF = pd.read_csv(path_AP)
data_GJF = pd.read_csv(path_GJ)
data_JBF = pd.read_csv(path_JB)

In [12]:
final_compiled_df = pd.concat([data_DPF, data_APF, data_GJF, data_JBF], ignore_index=True)

In [16]:
final_compiled_df = final_compiled_df.drop(['Unnamed: 0'], axis=1)

In [19]:
final_compiled_df = final_compiled_df.dropna()

In [21]:
final_compiled_df.to_csv('ML_dataset.csv', index=False)